# frozen_string_literal: true

ruby '3.4.3'
source 'https://rubygems.org'

gem 'logger', '~>1.7'
gem 'mime-types', '3.3.1'
gem 'puma', '~> 6.6'
gem 'rack', '~> 3.1'
gem 'rackup', '~> 2.2'
gem 'rerun', '~> 0.14', group: :development
gem 'rspec', '~> 3.0'
gem 'rubocop', '~> 1.39', require: false
gem 'sinatra', '~> 4.1'
