# frozen_string_literal: true

ruby '3.4.3'
source 'https://rubygems.org'

gem 'mime-types', '3.3.1'
gem 'puma', '< 6'
gem 'rack', '2.2.8.1'
gem 'rspec', '~> 3.0'
gem 'rubocop', '~> 1.39', require: false
gem 'logger', '~>1.7'
