name: lint

on: [push]

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: "3.1.2"
      - run: cd lujan.io
      - run: bundle exec rubocop .
